repos:
# Some pre-defined useful and standard pre-commit hooks checks
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
      -   id: check-yaml
          args: ['--unsafe']
      -   id: check-toml
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: debug-statements
      # it is now disabled
      #-   id: fix-encoding-pragma
      #    args: ["--remove"]
      -   id: mixed-line-ending
          args: ["--fix=lf"]

# flake8 linter preconfigured for compatibility with Black
  -   repo: https://github.com/pycqa/flake8
      rev: 7.3.0
      hooks:
      -   id: flake8
          name: "Flake8: critical"
          #args: ['--count', '--statistics'] #, '--select=E9,F63,F7,F82', '--show-source']
          additional_dependencies: [flake8-bugbear==21.9.2]

# The standard Black formatter
  -   repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
      -   id: black
          args: [--config=pyproject.toml]
          exclude: migrations/ venv/
          language_version: python3

# Automatically sort and formats Python imports
  -   repo: https://github.com/pycqa/isort
      rev: 6.0.1
      hooks:
      -   id: isort

# A complementary Static type checker
# TODO: not sure of compatibility/interest to couple with flake8
##  -   repo: https://github.com/pre-commit/mirrors-mypy
##      rev: v0.812
##      hooks:
##      -   id: mypy

# Automatically remove unused imports
# in-lieu-and-place of flake8
  -  repo: https://github.com/hadialqattan/pycln
     rev: 'v2.5.0'
     hooks:
     -   id: pycln
         args: ['.', "--all"]

  # Static analysis for checking compliance with Python docstring conventions
  -   repo: https://github.com/pycqa/pydocstyle
      rev: '6.3.0'
      hooks:
      -   id: pydocstyle
          files: ^src/

# TODO Run unit-tests
##  -   repo: local
##      hooks:
##      -   id: unittest
##          name: run unit tests
##          language: system
##          pass_filenames: false
##          entry: poetry run coverage run -m pytest
exclude: "src/urlchecker/providers/_template.py|tests/.*"
